apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: java-quarkus-gxeetroi
  janus-idp.io/tekton: java-quarkus-gxeetroi
  backstage.io/kubernetes-id: java-quarkus-gxeetroi
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: java-quarkus-gxeetroi
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
